CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS users(uuid UUID NOT NULL PRIMARY KEY, login VARCHAR(255) UNIQUE NOT NULL, encrypted_password VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS balance(user_id UUID NOT NULL PRIMARY KEY, balance BIGINT DEFAULT 0, withdraw BIGINT DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders( num_order VARCHAR(255) UNIQUE NOT NULL, time_order TIMESTAMPTZ NOT NULL, status VARCHAR(12) NOT NULL, debet_points BIGINT DEFAULT 0, credit_points BIGINT DEFAULT 0, user_id UUID NOT NULL REFERENCES balance (user_id));
